<?php
/**
 * WooCommerce hooks: strip default chrome, inject Amida product meta,
 * tiered pack selector, cart drawer upsells.
 *
 * @package Amida
 */

defined( 'ABSPATH' ) || exit;

/**
 * Remove default Storefront/WC chrome we replace with our own templates.
 */
add_action( 'init', function () {
	remove_action( 'woocommerce_before_main_content', 'woocommerce_breadcrumb', 20 );
	remove_action( 'woocommerce_sidebar', 'woocommerce_get_sidebar', 10 );
	remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_rating', 10 );
	remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_meta', 40 );
} );

/**
 * Render the image-masked compound name above the Add to Cart form on PDP.
 * The image is generated by the compliance plugin's Image_Masker.
 */
add_action( 'woocommerce_single_product_summary', function () {
	global $product;
	if ( ! $product instanceof WC_Product ) {
		return;
	}
	$real_name = get_post_meta( $product->get_id(), '_amida_real_compound', true );
	if ( ! $real_name ) {
		return;
	}
	$img = apply_filters( 'amida/compound_name_image', '', $product->get_id(), $real_name );
	if ( ! $img ) {
		return;
	}
	printf(
		'<img src="%s" alt="" class="pdp-compound-img" loading="lazy" aria-hidden="true" data-compound="%s">',
		esc_url( $img ),
		esc_attr( hash( 'sha256', $real_name ) )
	);
}, 15 );

/**
 * Add the RUO chip to product summaries.
 */
add_action( 'woocommerce_single_product_summary', function () {
	echo '<div style="margin:10px 0">';
	amida_ruo_chip();
	echo '</div>';
}, 8 );

/**
 * Replace the single-vial price with a tiered pack selector. Product meta
 * keys: _amida_pack_3, _amida_pack_5, _amida_pack_10.
 */
add_action( 'woocommerce_single_product_summary', function () {
	global $product;
	if ( ! $product instanceof WC_Product ) {
		return;
	}
	$single = (float) $product->get_regular_price();
	$pack3  = (float) get_post_meta( $product->get_id(), '_amida_pack_3', true );
	$pack5  = (float) get_post_meta( $product->get_id(), '_amida_pack_5', true );
	$pack10 = (float) get_post_meta( $product->get_id(), '_amida_pack_10', true );

	if ( ! $pack3 && ! $pack5 && ! $pack10 ) {
		return;
	}
	?>
	<div class="pdp-size-selector" role="radiogroup" aria-label="<?php esc_attr_e( 'Pack size', 'amida' ); ?>">
		<label class="pdp-size-option is-selected">
			<input type="radio" name="amida_pack" value="1" checked hidden>
			<div class="pdp-size-option__label"><?php esc_html_e( 'Single Vial', 'amida' ); ?></div>
			<div class="pdp-size-option__price"><?php echo esc_html( amida_price( $single ) ); ?></div>
		</label>
		<?php if ( $pack3 ) : ?>
			<label class="pdp-size-option">
				<input type="radio" name="amida_pack" value="3" hidden>
				<div class="pdp-size-option__label"><?php esc_html_e( '3-Pack', 'amida' ); ?></div>
				<div class="pdp-size-option__price"><?php echo esc_html( amida_price( $pack3 ) ); ?></div>
				<div class="pdp-size-option__savings">Save <?php echo esc_html( amida_pack_savings( $single, $pack3, 3 ) ); ?>%</div>
			</label>
		<?php endif; ?>
		<?php if ( $pack5 ) : ?>
			<label class="pdp-size-option">
				<input type="radio" name="amida_pack" value="5" hidden>
				<div class="pdp-size-option__label"><?php esc_html_e( '5-Pack', 'amida' ); ?></div>
				<div class="pdp-size-option__price"><?php echo esc_html( amida_price( $pack5 ) ); ?></div>
				<div class="pdp-size-option__savings">Save <?php echo esc_html( amida_pack_savings( $single, $pack5, 5 ) ); ?>%</div>
			</label>
		<?php endif; ?>
		<?php if ( $pack10 ) : ?>
			<label class="pdp-size-option">
				<input type="radio" name="amida_pack" value="10" hidden>
				<div class="pdp-size-option__label"><?php esc_html_e( '10-Pack', 'amida' ); ?></div>
				<div class="pdp-size-option__price"><?php echo esc_html( amida_price( $pack10 ) ); ?></div>
				<div class="pdp-size-option__savings">Save <?php echo esc_html( amida_pack_savings( $single, $pack10, 10 ) ); ?>%</div>
			</label>
		<?php endif; ?>
	</div>
	<?php
}, 20 );

/**
 * COA download card on PDP.
 */
add_action( 'woocommerce_single_product_summary', function () {
	global $product;
	if ( ! $product instanceof WC_Product ) {
		return;
	}
	$batch = get_post_meta( $product->get_id(), '_amida_batch', true );
	$coa   = get_post_meta( $product->get_id(), '_amida_coa_url', true );
	if ( ! $coa ) {
		return;
	}
	?>
	<div class="pdp-coa-card">
		<div>
			<div class="pdp-coa-card__title"><?php esc_html_e( 'Certificate of Analysis', 'amida' ); ?></div>
			<div class="pdp-coa-card__meta"><?php printf( esc_html__( 'Batch %s · HPLC verified · Third-party tested', 'amida' ), esc_html( $batch ) ); ?></div>
		</div>
		<a class="btn btn--ghost" href="<?php echo esc_url( $coa ); ?>" target="_blank" rel="noopener" data-log-coa="<?php echo esc_attr( $product->get_id() ); ?>"><?php esc_html_e( 'Download COA', 'amida' ); ?></a>
	</div>
	<?php
}, 22 );

/**
 * RUO notice on PDP.
 */
add_action( 'woocommerce_single_product_summary', function () {
	?>
	<div class="ruo-notice mt-2">
		<strong><?php esc_html_e( 'For Research Use Only', 'amida' ); ?></strong>
		<p style="margin:6px 0 0;font-size:.86rem;line-height:1.5">
			<?php esc_html_e( 'This compound is sold for laboratory and in-vitro research only. Not for human or animal consumption. Not FDA-approved for therapeutic or diagnostic use. Purchaser accepts all liability upon receipt.', 'amida' ); ?>
		</p>
	</div>
	<?php
}, 26 );

/**
 * Apply pack-price adjustment on add-to-cart. Stores qty as the pack size
 * and rewrites the cart line price to the tier.
 */
add_filter( 'woocommerce_add_cart_item_data', function ( $cart_item_data, $product_id ) {
	$pack = isset( $_POST['amida_pack'] ) ? absint( $_POST['amida_pack'] ) : 1;
	if ( ! in_array( $pack, [ 1, 3, 5, 10 ], true ) ) {
		$pack = 1;
	}
	$cart_item_data['amida_pack'] = $pack;
	return $cart_item_data;
}, 10, 2 );

add_filter( 'woocommerce_add_to_cart_quantity', function ( $quantity ) {
	$pack = isset( $_POST['amida_pack'] ) ? absint( $_POST['amida_pack'] ) : 1;
	return in_array( $pack, [ 1, 3, 5, 10 ], true ) ? $pack : $quantity;
}, 10 );

add_action( 'woocommerce_before_calculate_totals', function ( $cart ) {
	if ( is_admin() && ! defined( 'DOING_AJAX' ) ) {
		return;
	}
	foreach ( $cart->get_cart() as $item ) {
		$pack = $item['amida_pack'] ?? 1;
		if ( 1 === $pack ) {
			continue;
		}
		$pack_price = (float) get_post_meta( $item['product_id'], '_amida_pack_' . $pack, true );
		if ( $pack_price > 0 ) {
			$item['data']->set_price( $pack_price / $pack );
		}
	}
} );

/**
 * Remove SKUs from frontend display (but keep internally).
 */
add_filter( 'wc_product_sku_enabled', '__return_false' );

/**
 * Sanitize product image filenames on upload: hash and strip EXIF.
 */
add_filter( 'wp_handle_upload_prefilter', function ( $file ) {
	if ( empty( $file['name'] ) ) {
		return $file;
	}
	$ext       = pathinfo( $file['name'], PATHINFO_EXTENSION );
	$hash      = substr( hash( 'sha256', $file['name'] . microtime( true ) ), 0, 12 );
	$file['name'] = 'prod_' . $hash . '.' . strtolower( $ext );
	return $file;
} );
